<a href="https://colab.research.google.com/github/Dashnyam7/DIC/blob/main/Different_numpy_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
np.sum(a)

In [ ]:
a.sum()

Deal with data types

In [4]:
a.dtype   #data uusgehed automatoor int64 type uusdg

dtype('int64')

In [6]:
a = np.array([1, 2, 3], dtype=np.int16)   #gej data type solij bolno
a

array([1, 2, 3], dtype=int16)

In [7]:
a.astype(np.float16)   #float ruu huvirgaj bna

array([1., 2., 3.], dtype=float16)

Dimensional transformation: reshape ashiglan hemjees uurchilj bolno

In [ ]:
c1 = np.array([1, 2, 3, 4, 5, 6])
c1

In [15]:
c2 = c1.reshape((2,3))    #c1-iin hemjeeg uurchlunu
c2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c3 = c1.reshape((2, 4))   #aldaa

ravel -2D array-g 1D array bolgono

In [ ]:
c4 = c2.ravel()   #ravel element solihod c2-iinh dagaj soligdono
c4

In [17]:
c5 = c2.flatten()

Copy

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
a1 = a
a1[2] = 5
a1

In [ ]:
a   #a1g uurchluhud a-hamt uurchlugdsun

In [22]:
a2 = a.copy()
a2

array([1, 2, 5])

In [23]:
a2[2] = 10
a2

array([ 1,  2, 10])

In [24]:
a

array([1, 2, 5])

Sequence: 

In [ ]:
np.arange(10)

In [27]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

Random number

In [38]:
f_array = np.random.random((4, 2)) #0-1 hoorond
f_array

array([[0.18249173, 0.17545176],
       [0.53155137, 0.53182759],
       [0.63440096, 0.84943179],
       [0.72445532, 0.61102351]])

In [36]:
np.random.seed(123)   #seed function ashiglsnaar random toonuud uurchlugduhgui
np.random.random((4, 2))

array([[0.69646919, 0.28613933],
       [0.22685145, 0.55131477],
       [0.71946897, 0.42310646],
       [0.9807642 , 0.68482974]])

In [ ]:
np.random.seed(123)
np.random.randint(1, 10)    #1-10 hoorond random int

In [ ]:
np.random.seed(123)
np.random.randint(1, 10, (3, 5))  #1-10 hoornd 3x5 haritsaatai

In [ ]:
np.random.seed(123)
np.random.uniform(0.0, 5.0, size=(4, 2))

In [ ]:
np.random.seed(123)
np.random.uniform(size=(4, 2))

In [ ]:
np.random.seed(123)
np.random.randn(4, 3)   #standard normal tugelt

Various functions that generate arrays

In [51]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3, 4))

In [ ]:
np.ones((2, 3))

In [ ]:
np.eye(4)   #negj matrix uusgene

In [56]:
np.full(5,10)   #5 hemjeestei bugd 10

array([10, 10, 10, 10, 10])

In [57]:
np.full((2, 3), np.pi)

array([[3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265]])

In [58]:
np.array([1, 2, 3, np.nan])   #nan 

array([ 1.,  2.,  3., nan])

In [59]:
np.linspace(0, 1, 5)    #0-1g 4 huvaana

array([0.  , 0.25, 0.5 , 0.75, 1.  ])