<a href="https://colab.research.google.com/github/Dashnyam7/DIC/blob/main/NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Get difference between elements

In [8]:
l = np.array([ 1, 1, 5, 2, 4])
np.diff(l)

array([ 0,  4, -3,  2])

Concenatetion of elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a , b])

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[10, 20], [30, 40]])
np.concatenate([c, d], axis=1)

In [ ]:
e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.array([[10, 20, 30], [40, 50, 60]])
np.vstack([e, f])

Splitting a 2 dimensional array

In [ ]:
a = np.array([[1, 2, 10], [3, 4, 20], [5, 6, 30], [7, 8, 40]])
col1, col2 = np.hsplit(a, [2])  #ehnii 2 elementuudiig 1 bagana bolgong
col1

In [ ]:
col2

In [30]:
row1, row2 = np.vsplit(a, [2])   #ehnii 2 mur
row1

array([[ 1,  2, 10],
       [ 3,  4, 20]])

In [ ]:
row2

Transposing 2D array

Adding dimensions

In [ ]:
a

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])   #transpose
a.T

In [ ]:
a = np.array([1, 2, 3])
a[np.newaxis, : ]     #add x directions

In [ ]:
a[: , np.newaxis]     #add y directions

Generate grid data

In [41]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7])
xx, yy = np.meshgrid(x, y)
xx

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [39]:
yy

array([[5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])