<a href="https://colab.research.google.com/github/Dashnyam7/DIC/blob/main/Scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is scikit learn

scikit-learn is a library for machine learning in Python.
Preprocessing:
-Dealing with missing values
-Numericalization of categorical variables
-Feature normalization

## Dealing with missing values

In [1]:
import numpy as np
import pandas as pd
df = pd.DataFrame(
  {
    'A': [1, 2, 3, 4, np.nan],
    'B': [10, np.nan, 30, 40, 50],
    'C': [np.nan, 200, 300, 400, 500]
  }
)
df

A     B      C
0  1.0  10.0    NaN
1  2.0   NaN  200.0
2  3.0  30.0  300.0
3  4.0  40.0  400.0
4  NaN  50.0  500.0

### Exclude missing values

Check contain missing value isnull()

In [2]:
df.isnull()   #missing valur-True

A      B      C
0  False  False   True
1  False   True  False
2  False  False  False
3  False  False  False
4   True  False  False

In [3]:
df.dropna()   #missing value-g ustgah

A     B      C
2  3.0  30.0  300.0
3  4.0  40.0  400.0

### Missing value imputation

In [5]:
from sklearn.impute import SimpleImputer

At this time, strategyspecify the value to complement the parameter of the argument. Here we specify to
impute with the mean .mean

In [6]:
imp = SimpleImputer(strategy='mean')

fit()  This time the average value is SimpleImputercalculated and the result is stored in the instance.

In [7]:
imp.fit(df)

SimpleImputer()

transformuse the method to perform the process of imputing the missing values ​​with the mean

In [8]:
imp.transform(df)

array([[  1. ,  10. , 350. ],
       [  2. ,  32.5, 200. ],
       [  3. ,  30. , 300. ],
       [  4. ,  40. , 400. ],
       [  2.5,  50. , 500. ]])

You can also specify (median ), (mode)

In [12]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='median')
imp.fit(df)
imp.transform(df)

array([[  1. ,  10. , 350. ],
       [  2. ,  35. , 200. ],
       [  3. ,  30. , 300. ],
       [  4. ,  40. , 400. ],
       [  2.5,  50. , 500. ]])

## Numericalization of categorical variables

In [13]:
df = pd.DataFrame([[23, 'male'],
                   [43, 'female'],
                   [31, 'male'],
                   [35, 'female'],
                   [40, 'male']],
                   columns=['age', 'sex'])
df

age     sex
0   23    male
1   43  female
2   31    male
3   35  female
4   40    male

Of this data, the sexcolumn malevalues female​​are categorical variables because they can be classified by and

Categorical datag toon utga ruu shiljuuleh ba ingesneer machine surch chadna

### label encoding

Ene arga ni angilal burt toon utga onoodog. jishee ni male-0

#### preprocessingLabelEncoder

In [14]:
from sklearn.preprocessing import LabelEncoder  #LabelEncodercreate an instance of the class

sex we encode the column values

In [15]:
le = LabelEncoder()

In [16]:
le.fit(df['sex'])

LabelEncoder()

transformuse a method to sexapply the encoded result to the column value

In [17]:
le.transform(df['sex'])

array([1, 0, 1, 0, 1])

classes_attributes to see which values ​​have been encoded

In [19]:
le.classes_

array(['female', 'male'], dtype=object)

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['sex'])
le.transform(df['sex'])

array([1, 0, 1, 0, 1])

#### One-hot encoding

Categoriin huvisagchiin turultei ijil toonii bagana uusgedeg

In [21]:
df = pd.DataFrame([[23, 'male'],
                   [43, 'female'],
                   [31, 'male'],
                   [35, 'female'],
                   [40, 'male']],
                   columns=['age', 'sex'])
df

age     sex
0   23    male
1   43  female
2   31    male
3   35  female
4   40    male

preprocessingImport module OneHotEncoderclass and composemodule class from scikit-learn to perform the one-hot encoding process ColumnTransformer

In [22]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ColumnTransformerBy using classes, we can perform different operations on each column of a DataFrame

First, ColumnTransformercreate an instance of the class.

In [27]:
ohe = ColumnTransformer([("OneHotEncoder", OneHotEncoder(), [1])], remainder = 'passthrough')

In [28]:
df_ohe = df.copy()
ohe.fit_transform(df_ohe)

array([[ 0.,  1., 23.],
       [ 1.,  0., 43.],
       [ 0.,  1., 31.],
       [ 1.,  0., 35.],
       [ 0.,  1., 40.]])

### Feature normalization

Feature normalization is the process of equalizing the size of features

#### Variance normalization

In [29]:
  import pandas as pd
df = pd.DataFrame({
  'data1': [1, 2, 3, 4, 5],
  'data2': [1000, 3000, 3500, 5000, 7000]
})
df

data1  data2
0      1   1000
1      2   3000
2      3   3500
3      4   5000
4      5   7000

##### Decentralized regularization


Variance normalization is a method of transforming features so that the mean value of features is 0 and the standard deviation is 1

In [31]:
from sklearn.preprocessing import StandardScaler

StandardScalercreate an instance of the class

In [32]:
scaler = StandardScaler()

In [33]:
scaler.fit_transform(df)

array([[-1.41421356, -1.44280393],
       [-0.70710678, -0.44776674],
       [ 0.        , -0.19900744],
       [ 0.70710678,  0.54727045],
       [ 1.41421356,  1.54230764]])

##### min-max normalization

Min-max normalization is a method of transforming features so that their maximum value is 1 and their minimum value is 0

In [35]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit_transform(df)

array([[0.        , 0.        ],
       [0.25      , 0.33333333],
       [0.5       , 0.41666667],
       [0.75      , 0.66666667],
       [1.        , 1.        ]])