<a href="https://colab.research.google.com/github/Dashnyam7/DIC/blob/main/Various_functions_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Universal function

In [2]:
a = np.array([[-1, -2, -3, 4, 5], [6, 7, -8, -9, -10]])
np.abs(a)   #abs utga

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

Broadcast

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([[10, 20, 30], [40, 50, 60]])
d = np.array([[1], [2], [3]])

In [4]:
a + 10

array([11, 12, 13])

In [5]:
a + b

array([5, 7, 9])

In [6]:
a + c #1D array + 2D array = suuliin arrayuud nemne

array([[11, 22, 33],
       [41, 52, 63]])

In [7]:
a + d   #1row deer #row nemehed 

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [8]:
a = np.array([1, 2, 3])
a_inf = np.array([0, 2, 0])
a / a_inf     #toog 0t huvaaval inf-ur dun

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([inf,  1., inf])

In [ ]:
a_inf

In [10]:
a / (a_inf + 1e-6)

array([1.000000e+06, 9.999995e-01, 3.000000e+06])

Dot product

In [16]:
a = np.array([1, 2, 3])
b = np.array([[-1, -2, -3], [4, 5, 6]])
a

array([1, 2, 3])

In [12]:
np.dot(b, a)

array([-14,  32])

In [13]:
b @ a   #inner product

array([-14,  32])

In [18]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[-1, -2], [3, 4], [5, 6]])

In [19]:
np.dot(a, b)

array([[20, 24],
       [41, 48]])

In [20]:
np.dot(b, a)

array([[ -9, -12, -15],
       [ 19,  26,  33],
       [ 29,  40,  51]])

Judgement: compare hj true false

In [21]:
a = np.array([[-1, -2], [3, 4], [5, 6]])
a > 0

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [22]:
np.count_nonzero(a > 0 )    #0-ees ih heden element bgaa

4

In [24]:
np.sum(a > 3)

3

In [25]:
np.any(a >= 5)    #ali neg ni >=

True

In [26]:
np.all(a > 0)   #bugd >0

False

In [27]:
a[a > 0]    #0-ees ihuudiig awah

array([3, 4, 5, 6])

Compare array between

In [32]:
a = np.array([[1, 2, 3], [4, 2, 6]])
b = np.array([[1, 3, 5], [2, 4, 6]])
c = np.array([1, 2, 3])
a == b    #elementuudiig 1 burchlen

array([[ True, False, False],
       [False, False,  True]])

In [33]:
a == c

array([[ True,  True,  True],
       [False,  True, False]])

In [34]:
np.allclose(a, b)

False

In [35]:
np.allclose(a, b, atol=10)

True